import turtle, random

turtle.setup(800, 500)
turtle.title("Turtle Race")
turtle.bgcolor("forestgreen")
turtle.speed(0)

turtle .penup()
turtle.goto(-100, 205)
turtle.color("white")
turtle.write("TURTLE RACE", font=("Arial", 20, "bold"))

turtle.goto(-350, 200)
turtle.pendown()
turtle.color("chocolate")
turtle.begin_fill()
for i in range(2):
  turtle.forward(700)
  turtle.right(90)
  turtle.forward(400)
  turtle.right(90)
turtle.end_fill()

gap_size = 20
turtle.shape("square")
turtle.penup()

turtle.color("white")
for i in range(10):
  turtle.goto(250, (170 - (i * gap_size * 2)))
  turtle.stamp()

for i in range(10):
  turtle.goto(250 + gap_size, ((210 - gap_size) - (i * gap_size * 2)))
  turtle.stamp()

turtle.color("black")
for i in range(10):
  turtle.goto(250, (190 - (i * gap_size * 2)))
  turtle.stamp()

for i in range(10):
  turtle.goto(251 + gap_size, ((190 - gap_size) - (i * gap_size * 2)))
  turtle.stamp()

blue_turtle = turtle.Turtle()
blue_turtle.color("blue")
blue_turtle.shape("turtle")
blue_turtle.shapesize(1.5)
blue_turtle.penup()
blue_turtle.goto(-300, 150)

purple_turtle = turtle.Turtle()
purple_turtle.color("purple")
purple_turtle.shape("turtle")
purple_turtle.shapesize(1.5)
purple_turtle.penup()
purple_turtle.goto(-300, 50)

yellow_turtle = turtle.Turtle()
yellow_turtle.color("yellow")
yellow_turtle.shape("turtle")
yellow_turtle.shapesize(1.5)
yellow_turtle.penup()
yellow_turtle.goto(-300, -50)

green_turtle = turtle.Turtle()
green_turtle.color("lime")
green_turtle.shape("turtle")
green_turtle.shapesize(1.5)
green_turtle.penup()
green_turtle.goto(-300, -150)

while blue_turtle.xcor() <= 230 and purple_turtle.xcor() <= 230 and yellow_turtle.xcor() <= 230 and green_turtle.xcor() <= 230:
 blue_turtle.forward(random.randint(1,7))
 purple_turtle.forward(random.randint(1,7))
 yellow_turtle.forward(random.randint(1,7))
 green_turtle.forward(random.randint(1,7))

if blue_turtle.xcor() > purple_turtle.xcor() and blue_turtle.xcor() > yellow_turtle.xcor() and blue_turtle.xcor() > green_turtle.xcor():
  print('Blue Turtle is the Winner!!')
  bt = turtle.Turtle()
  bt.penup()
  bt.hideturtle()
  bt.goto(-120, 105)
  bt.color("Blue")
  bt.write("Blue Turtle Wins", font=("Arial", 20, "bold"))
  blue_turtle.goto(0, 0)
  for t in range(72):
      blue_turtle.right(10)
      blue_turtle.shapesize(4)

elif purple_turtle.xcor() > blue_turtle.xcor() and purple_turtle.xcor() > yellow_turtle.xcor() and purple_turtle.xcor() > green_turtle.xcor():
  print('Purple Turtle is the Winner!!')
  pt = turtle.Turtle()
  pt.penup()
  pt.hideturtle()
  pt.goto(-120, 105)
  pt.color("purple")
  pt.write("Purple Turtle Wins", font=("Arial", 20, "bold"))
  purple_turtle.goto(0, 0)
  for t in range(72):
      purple_turtle.right(10)
      purple_turtle.shapesize(4)

elif yellow_turtle.xcor() > purple_turtle.xcor() and yellow_turtle.xcor() > blue_turtle.xcor() and yellow_turtle.xcor() > green_turtle.xcor():
  print('Yellow Turtle is the Winner!!')
  yt = turtle.Turtle()
  yt.penup()
  yt.hideturtle()
  yt.goto(-120, 105)
  yt.color("yellow")
  yt.write("Yellow Turtle Wins", font=("Arial", 20, "bold"))
  yellow_turtle.goto(0, 0)
  for t in range(72):
      yellow_turtle.right(10)
      yellow_turtle.shapesize(4)

else:
  print('Green Turtle is the Winner!!')
  gt = turtle.Turtle()
  gt.penup()
  gt.hideturtle()
  gt.goto(-120, 105)
  gt.color("lime")
  gt.write("Green Turtle Wins", font=("Arial", 20, "bold"))
  green_turtle.goto(0, 0)
  for t in range(72):
      green_turtle.right(10)
      green_turtle.shapesize(4)

turtle.exitonclick()


import turtle,random
turtle.setup(800,500)
win = turtle.Screen()
win.title('turtle race!!')
win.bgcolor('#1b6e00')
#------------track turtle-----------------------
track = turtle.Turtle()
track.hideturtle()
track.pencolor('#D2691E')
track.speed(0)
track.pensize(150)
track.goto(500,0)
track.goto(-500,0)
track.hideturtle()
track.penup()
track.pensize(20)
track.pencolor('yellow')
track.goto(310,100)
track.pendown()
track.goto(310,-100)
#------------tree creation----------------------
track.penup()
track.showturtle()
track.goto(200,200)
track.pensize(2)
track.pendown()
track.pencolor('#013214')
track.lt(90)
track.fd(10)
track.rt(90)
track.fd(10)
track.lt(120)
track.fd(15)
track.rt(110)
track.fd(5)
track.lt(110)
track.fd(15)
track.penup()
track.goto(200,200)
track.pendown()
track.rt(30)
track.fd(10)
track.lt(90)
track.fd(10)
track.rt(120)
track.fd(15)
track.lt(110)
track.fd(5)
track.rt(110)
track.fd(15)

track.rt(55)
track.penup()
track.showturtle()
track.goto(200,-200)
track.pensize(2)
track.pendown()
track.pencolor('#013214')
track.lt(90)
track.fd(10)
track.rt(90)
track.fd(10)
track.lt(120)
track.fd(15)
track.rt(110)
track.fd(5)
track.lt(110)
track.fd(15)
track.penup()
track.goto(200,-200)
track.pendown()
track.rt(30)
track.fd(10)
track.lt(90)
track.fd(10)
track.rt(120)
track.fd(15)
track.lt(110)
track.fd(5)
track.rt(110)
track.fd(15)

track.rt(55)
track.penup()
track.showturtle()
track.goto(105,150)
track.pensize(2)
track.pendown()
track.pencolor('#013214')
track.lt(90)
track.fd(10)
track.rt(90)
track.fd(10)
track.lt(120)
track.fd(15)
track.rt(110)
track.fd(5)
track.lt(110)
track.fd(15)
track.penup()
track.goto(105,150)
track.pendown()
track.rt(30)
track.fd(10)
track.lt(90)
track.fd(10)
track.rt(120)
track.fd(15)
track.lt(110)
track.fd(5)
track.rt(110)
track.fd(15)

track.rt(55)
track.penup()
track.showturtle()
track.goto(200,200)
track.pensize(2)
track.pendown()
track.pencolor('#013214')
track.lt(90)
track.fd(10)
track.rt(90)
track.fd(10)
track.lt(120)
track.fd(15)
track.rt(110)
track.fd(5)
track.lt(110)
track.fd(15)
track.penup()
track.goto(200,200)
track.pendown()
track.rt(30)
track.fd(10)
track.lt(90)
track.fd(10)
track.rt(120)
track.fd(15)
track.lt(110)
track.fd(5)
track.rt(110)
track.fd(15)

track.rt(55)
track.penup()
track.showturtle()
track.goto(200,200)
track.pensize(2)
track.pendown()
track.pencolor('#013214')
track.lt(90)
track.fd(10)
track.rt(90)
track.fd(10)
track.lt(120)
track.fd(15)
track.rt(110)
track.fd(5)
track.lt(110)
track.fd(15)
track.penup()
track.goto(200,200)
track.pendown()
track.rt(30)
track.fd(10)
track.lt(90)
track.fd(10)
track.rt(120)
track.fd(15)
track.lt(110)
track.fd(5)
track.rt(110)
track.fd(15)

track.rt(55)
track.penup()
track.showturtle()
track.goto(200,200)
track.pensize(2)
track.pendown()
track.pencolor('#013214')
track.lt(90)
track.fd(10)
track.rt(90)
track.fd(10)
track.lt(120)
track.fd(15)
track.rt(110)
track.fd(5)
track.lt(110)
track.fd(15)
track.penup()
track.goto(200,200)
track.pendown()
track.rt(30)
track.fd(10)
track.lt(90)
track.fd(10)
track.rt(120)
track.fd(15)
track.lt(110)
track.fd(5)
track.rt(110)
track.fd(15)

track.rt(55)
track.penup()
track.showturtle()
track.goto(-200,-200)
track.pensize(2)
track.pendown()
track.pencolor('#013214')
track.lt(90)
track.fd(10)
track.rt(90)
track.fd(10)
track.lt(120)
track.fd(15)
track.rt(110)
track.fd(5)
track.lt(110)
track.fd(15)
track.penup()
track.goto(-200,-200)
track.pendown()
track.rt(30)
track.fd(10)
track.lt(90)
track.fd(10)
track.rt(120)
track.fd(15)
track.lt(110)
track.fd(5)
track.rt(110)
track.fd(15)

#------------turtle creation and setup----------
sam = turtle.Turtle()
sam.penup()
sam.speed(0)
sam.shape('turtle')
sam.color('red')
sam.turtlesize(1,1)
sam.hideturtle()
sam.goto(-350,-20)
sam.showturtle()

flavio = turtle.Turtle()
flavio.penup()
flavio.speed(0)
flavio.shape('turtle')
flavio.color('#FADFAE')
flavio.turtlesize(1,1)
flavio.hideturtle()
flavio.goto(-350,-60)
flavio.showturtle()

tony = turtle.Turtle()
tony.penup()
tony.speed(0)
tony.shape('turtle')
tony.color('black')
tony.turtlesize(1,1)
tony.hideturtle()
tony.goto(-350,60)
tony.showturtle()

tt = turtle.Turtle()
tt.penup()
tt.speed(0)
tt.shape('turtle')
tt.color('green')
tt.turtlesize(1,1)
tt.hideturtle()
tt.goto(-350,20)
tt.showturtle()

while tony.xcor() <= 300 and flavio.xcor() <= 300 and sam.xcor() <= 300 and tt.xcor() <= 300:
   tony.fd(random.randint(1, 20))
   flavio.fd(random.randint(1, 20))
   sam.fd(random.randint(1, 20))
   tt.fd(random.randint(1, 20))

if tt.xcor() > tony.xcor() and tt.xcor() > sam.xcor() and tt.xcor() > flavio.xcor():
  track.penup()
  track.goto(-50, 100)
  track.color("green")
  track.write("Taylor Wins", font=("Arial", 20, "bold"))
  tt.goto(0,0)
  tt.turtlesize(4)


elif tony.xcor() > tt.xcor() and tony.xcor() > sam.xcor() and tony.xcor() > flavio.xcor():
  track.penup()
  track.goto(-50, 100)
  track.color("black")
  track.write("Tony Wins", font=("Arial", 20, "bold"))
  tony.goto(0,0)
  tony.turtlesize(4)

elif sam.xcor() > tt.xcor() and sam.xcor() > tony.xcor() and sam.xcor() > flavio.xcor():
  track.penup()
  track.goto(-50, 100)
  track.color("red")
  track.write("Sam Wins", font=("Arial", 20, "bold"))
  sam.goto(0,0)
  sam.turtlesize(4)

else:
  track.penup()
  track.goto(-50, 100)
  track.color("#FADFAE")
  track.write("flavio Wins", font=("Arial", 20, "bold"))
  flavio.goto(0,0)
  flavio.turtlesize(4)




